import { Button } from "@/components/ui/button";
import { QueryProvider } from "@/providers/query-provider";
import { MessageSquareMore } from "lucide-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainFooter } from "@/components/app/main-footer";
import { MainMenu } from "@/components/app/main-menu";
import { ModalProvider } from "@/providers/modal-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <MainMenu />
        <main className="p-5 ">
          <QueryProvider>
            <ModalProvider>{children}</ModalProvider>
          </QueryProvider>
        </main>
        <MainFooter />
      </body>
    </html>
  );
}
